"""
Django settings for packing_project project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, set the SECRET_KEY environment variable
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-d@^^w7f59xjw^h76e2)8ji2qk#%y!z&9-cu2y3o!9r@84rc#s1",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() in ("true", "1", "yes")

# Allowed hosts - comma-separated list
ALLOWED_HOSTS: list[str] = list(
    filter(None, os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(","))
)

# CSRF trusted origins - required for HTTPS behind proxy
# Example: CSRF_TRUSTED_ORIGINS=https://myapp.example.com,https://www.myapp.example.com
_csrf_origins = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS: list[str] = list(filter(None, _csrf_origins.split(",")))


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "core",
    "accounts",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "packing_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "accounts.context_processors.auth_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "packing_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# In production with Docker, the database is stored in /app/data/db.sqlite3

_db_path = os.environ.get("DATABASE_PATH", str(BASE_DIR / "db.sqlite3"))

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": _db_path,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Whitenoise configuration for efficient static file serving
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication settings
LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "core:dashboard"
LOGOUT_REDIRECT_URL = "accounts:login"

# Django REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}


# Security settings for production (behind nginx with SSL termination)
# Trust X-Forwarded-Proto header from nginx proxy
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Secure cookies - enabled by default for production
# Set SECURE_COOKIES=False only for local HTTP testing
_secure_cookies = os.environ.get("SECURE_COOKIES", "True").lower() in ("true", "1", "yes")
SESSION_COOKIE_SECURE = _secure_cookies
CSRF_COOKIE_SECURE = _secure_cookies


# =============================================================================
# Authentication Configuration
# =============================================================================

# Enable/disable authentication methods via environment variables
PASSWORD_LOGIN_ENABLED = os.environ.get("PASSWORD_LOGIN_ENABLED", "True").lower() in (
    "true",
    "1",
    "yes",
)
OIDC_ENABLED = os.environ.get("OIDC_ENABLED", "False").lower() in ("true", "1", "yes")

# Authentication backends - always include Django's ModelBackend for password login
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

# =============================================================================
# OIDC Configuration (Pocket ID / OpenID Connect)
# =============================================================================

if OIDC_ENABLED:
    # Add OIDC app and backend
    INSTALLED_APPS.append("mozilla_django_oidc")
    AUTHENTICATION_BACKENDS.insert(0, "accounts.oidc.PocketIDAuthBackend")

    # Add session refresh middleware to handle token expiry
    MIDDLEWARE.append("mozilla_django_oidc.middleware.SessionRefresh")

    # OIDC Provider Configuration
    OIDC_OP_BASE_URL = os.environ.get("OIDC_OP_BASE_URL", "")
    OIDC_RP_CLIENT_ID = os.environ.get("OIDC_RP_CLIENT_ID", "")
    OIDC_RP_CLIENT_SECRET = os.environ.get("OIDC_RP_CLIENT_SECRET", "")

    # OIDC endpoints - derived from base URL (Pocket ID uses /api/oidc/ prefix)
    OIDC_OP_AUTHORIZATION_ENDPOINT = f"{OIDC_OP_BASE_URL}/authorize"
    OIDC_OP_TOKEN_ENDPOINT = f"{OIDC_OP_BASE_URL}/api/oidc/token"
    OIDC_OP_USER_ENDPOINT = f"{OIDC_OP_BASE_URL}/api/oidc/userinfo"
    OIDC_OP_JWKS_ENDPOINT = f"{OIDC_OP_BASE_URL}/.well-known/jwks.json"

    # OIDC signing algorithm (Pocket ID uses RS256)
    OIDC_RP_SIGN_ALGO = "RS256"

    # Request scopes - openid is required, profile/email for user info, groups for admin mapping
    OIDC_RP_SCOPES = "openid profile email groups"

    # Create Django user on first OIDC login
    OIDC_CREATE_USER = True

    # Store OIDC tokens in session (needed for logout and token refresh)
    OIDC_STORE_ACCESS_TOKEN = True
    OIDC_STORE_ID_TOKEN = True

    # Admin/staff group mapping from OIDC groups claim
    OIDC_ADMIN_GROUP = os.environ.get("OIDC_ADMIN_GROUP", "admin")
    OIDC_STAFF_GROUP = os.environ.get("OIDC_STAFF_GROUP", "staff")
